#!/bin/sh


echo "// generated by $0" > src/re_vec.rs
echo "use regex::bytes::Regex;" >> src/re_vec.rs
echo "use regex::Error;" >> src/re_vec.rs
echo "use util::regex;" >> src/re_vec.rs
echo "" >> src/re_vec.rs
echo "pub fn re_vec() -> Vec<Result<Regex, Error>> {" >> src/re_vec.rs
echo "vec![" >> src/re_vec.rs
cat ../scraped_regex.tsv | awk -F$'\t' '{ print "regex(" $3 ")," }' >> src/re_vec.rs
echo "]" >> src/re_vec.rs
echo "}" >> src/re_vec.rs
